### ISSUE TITLE
Crash no app ao chamar o método stoneValidation

### ISSUE THREAD

**Issue by igortrinidad** [stone-payments/cordova-plugin-stone-sdk#12]
A alegria de ter conseguido enfim rodar o plugin não durou muito viu @filpgame ... Não consegui rodar os métodos validation e transaction está dando erro também... O deviceSelected rodou de boa...

Esse é o código de um estabelecimento meu, tentei com string e número...

Veja nosso código:

```
			stoneValidation: function(){
			    let that = this
			

			    stone_sdk.validation('121378283', function(){

			    }, function(){
			    	
			    });
			},


			selectPinpad: function(device){
        	    let that = this

        	    let pinpad = device.name + '_' + device.address;

        		that.ppinpad_selected = pinpad;
        		localStorage.setItem('pinpad_selected', JSON.stringify(pinpad));

        		//Conecta o app no pinpad
        		stone_sdk.deviceSelected(pinpad, function(){

        		}, function(){
        			
        		});
        	    
        	},

        	transactionForTest: function(){
        	    let that = this
        	
        	    stone_sdk.transaction('0.01', 'DEBIT', '1', function(){
        	    	console.log('foi')
        		}, function(){
        			console.log('nao foi')
        		});
        	},
```

![screenshot_20180112-040612](https://user-images.githubusercontent.com/13478652/34862018-2dba3f4e-f74f-11e7-8802-afcb1eed6e6e.png)

**Comment by igortrinidad** [comment]
@filpgame e ai, conseguiu verificar o erro no método validation? É possível encontrar essa SDK aberta para fazermos alguns testes aqui?

**Comment by filpgame** [comment]
Corrigido! 26e6e4ab7cecc60c708922c50833f11e84b89d13
