### ISSUE TITLE
Metodos de pagamento para vouchers

### ISSUE THREAD

**Issue by igortrinidad** [stone-payments/cordova-plugin-stone-sdk#13]
@filpgame , vou aproveitar que você está no SDK e abrir uma issue aqui sobre os métodos de pagamento.

O Mario Dias, havia me fala que nós poderiamos receber outros métodos de pagamento no pinpad, porém vi que só tem a verificação das strings para "DEBIT" e "CREDIT" no stoneSDK.java, quais parametros vamos passar na transaction para os métodos de pagamento dos vouchers por exemplo: Alelo, Sodexo, Ticket... Essas ultimas duas últimas o Mario disse que estava em processo de homologação...

Abs

**Comment by filpgame** [comment]
Opa @igortrinidad, Para transações voucher é só usar o `DEBIT`
