### ISSUE TITLE
Generic error na validação do StoneCode

### ISSUE THREAD

**Issue by limatheus** [stone-payments/cordova-plugin-stone-sdk#14]
Olá @filpgame, acabei de realizar um teste aqui após os novos commits e estamos recebendo o erro abaixo na hora de validar StoneCode.

![error](https://s14.postimg.org/i6mh0s6n5/Screenshot_2018-01-15-17-21-48.jpg)

O erro é o mesmo apresentado em nossa aplicação e no demo de vocês.

Você tem idéia do que pode ser?

Abraço

**Comment by filpgame** [comment]
Verifica com time de integração se esse é seu stoneCode mesmo. esse erro pode ocorrer quando o stone code é inválido

**Comment by igortrinidad** [comment]
Opa @filpgame , beleza?

Que show que esta fluindo o plugin! 
Sobre o Stone code, esse é o que uso atualmente no meu estabelecimento, veja anexo. Precisa fazer alguma requisição especifica para habilitar o uso na api?

De qualquer forma, vou mandar email para o integracoes@ e verificar também...

Valeu

![captura de tela 2018-01-16 as 11 23 38](https://user-images.githubusercontent.com/13478652/34991211-ed2825fe-faaf-11e7-9280-5a50887fd740.png)

**Comment by filpgame** [comment]
Hmm, pode ser que o stone code não esteja habilitado a fazer transações mobile. Manda um e-mail pra  integrações que eu aciono a galera aqui!

**Comment by igortrinidad** [comment]
Show @filpgame, já mandei o email, se puder olhar por favor será ótimo!

Abs



Em 16 de janeiro de 2018 às 12:39:45, Felipe Rodrigues (notifications@github.com<mailto:notifications@github.com>) escreveu:

Hmm, pode ser que o stone code não esteja habilitado a fazer transações mobile. Manda um e-mail pra integrações que eu aciono a galera aqui!

**Comment by igortrinidad** [comment]
Opa @filpgame , verifiquei com o Mario Dias e ele me disse que nosso Stone Code está habilitado para produção.

Existe alguma forma de passar a configuração de ambiente de produção e homologação? Eu não entendi muito bem como fazer essa configuração com o plugin.

Att

**Comment by filpgame** [comment]
Subi uma alteração adicionando um novo método para setar o ambiente da SDK, estou agora fazendo a demo pra demostrar o uso do método :)

**Comment by igortrinidad** [comment]
Aow @filpgame que notícia boa! Já solicitei o stone code de produção junto ao canal meajuda mas vou testando aqui com o stone code que eu tenho... Logo logo te damos um feedback ai, valeu de mais!! 👏

**Comment by filpgame** [comment]
`PRODUCTION` e `SANDBOX`

**Comment by igortrinidad** [comment]
Nice @filpgame!

**Comment by filpgame** [comment]
@limatheus 
estranho, na demo (que inclusive atualizei com o set do ambiente) consegui testar normalmente

**Comment by limatheus** [comment]
@filpgame, testei várias vezes e o erro é sempre o mesmo.

![](https://s13.postimg.org/kj6op7q7b/Screenshot_2018-01-18-18-58-45_1.jpg)

**Comment by limatheus** [comment]
@filpgame, com o StoneCode correto, conseguimos avançar.
Estou fechando este issue para abrir outro relacionado a transaction.
