### ISSUE TITLE
Cancelamento de transação

### ISSUE THREAD

**Issue by igortrinidad** [stone-payments/cordova-plugin-stone-sdk#19]
Opa @filpgame, beleza? 

Cara, o @limatheus alterou os métodos de retorno da lista de transações e da transação no plugin, retornando o objeto da transação completo ao invés da string apenas com algumas infos.

Isso é muito importante pois como envolve transferencia de recursos nós precisamos de mais infos como o código de autorização, `recipientTransactionIdentification`  entre outros dados importantes para qualquer auditoria que precisemos implantar futuramente.

Mas vamos lá, visto que o id da lista de transação é apenas um ordenador das transações realizadas no determinado device, o método de efetuar o cancelamento de uma transação espera o id da transação no device, porém dentro da SDK no CancellationProvider o método utiliza o `recipientTransactionIdentification` para enviar o cancelamento.

Como o id que espera no método da transação é apenas um ordenador e ele pode ser apagado quando se limpa os dados do app / desinstala o app... Gostaria de saber se é possível alterar o método na SDK para esperar o `recipientTransactionIdentification` ao invés do ID da transação no device...

Assim a transação poderá ser cancelada mesmo de outros dispositivos, caso haja algum problema no device e mesmo poderá oferecer a descentralização dessa operação que poderá ser realizada por outros devices com acesso à lista de transações como no caso de painel admin que será implementado.

Veja a viabilidade desta alteração, valeu!

**Comment by filpgame** [comment]
Olá @igortrinidad, 
Esta é uma melhoria que já está mapeada no nosso backlog. A ideia é que o cliente da SDK passe o objeto da transação para o provider (que pode ser montado de qualquer lugar). 
Vou dar aumentar a prioridade para ela para entrar na próxima versão das SDKs!

**Comment by igortrinidad** [comment]
Show @filpgame ! Estamos afinando as coisas aqui também, vamos reportando o que acharmos, mas agora está fluindo bem! 🙏 

Abs

**Comment by limatheus** [comment]
@filpgame tudo bem?
Alguma novidade sobre este assunto?
Atualmente só podemos cancelar a transação no dispositivo onde a mesma foi realizada, como temos vários dispositivos, seria interessante poder cancelar uma transação de qualquer dispositivo utilizando outro parâmetro que não seja o `idTransaction_amountTransaction_statusTransaction`, nós armazenamos o objeto transaction no db, então temos todos os atributos disponíveis para utilizar.
