### ISSUE TITLE
Erro nas transações CREDIT

### ISSUE THREAD

**Issue by igortrinidad** [stone-payments/cordova-plugin-stone-sdk#20]
As transações no metódo CREDIT não estão funcionando...

![screenshot_20180123-200147](https://user-images.githubusercontent.com/13478652/35362486-aa0a670c-014c-11e8-93dc-03941a2bf174.png)

**Comment by limatheus** [comment]
@filpgame e @igortrinidad, acertei onde estava dando o erro, era a string que ele estava esperando.
Passando `ONE_INSTALMENT`, `TWO_INSTALMENT_NO_INTEREST` etc.. funcionou
