### ISSUE TITLE
Impressão Pos Ingenico A8

### ISSUE THREAD

**Issue by ManoloReis** [stone-payments/cordova-plugin-stone-sdk#24]
Boa tarde,

Estou tentando implementar a impressão no Pos A8 da Ingenico, porem sem sucesso.

Ao executar o PosPrintProvider recebo o erro **UNEXPECTED_STATUS_COMMAND**.

Os demais providers funcionam corretamente, poderiam me ajudar?

Grato

**Comment by ManoloReis** [comment]
Fechando este issue!
Aproveitando que o cliente desistiu da Stone, graças a Deus não vou precisar mexer com algo relacionado a vocês.
Péssimo suporte.

**Comment by brdacon1** [comment]
Estou com o mesmo problema usando o deeplink porém não encontro documentação ou qualquer informação da APOS A8 para fazer as impressões de comprovante.
