### ISSUE TITLE
Instalação e build no Android

### ISSUE THREAD

**Issue by igortrinidad** [stone-payments/cordova-plugin-stone-sdk#8]
Olá pessoal,

Acabei enviando um pull com a adição do package.json para tentar solucionar o problema de instalação do plugin na aplicação Cordova.

Adicionei um package.json simples que tirei baseado em outros plugins para conseguir instalar, a instalação ocorreu sem problemas mas por algum motivo na hora de gerar o build estava dando erro na classe stone do SDK.

Vocês conseguem me ajudar por favor?

Agradeço desde já a atenção de vocês.

Bom final de semana!

**Comment by limatheus** [comment]
@victormendes5 nós estamos usando o cordova, para testar tentei rodar o demo que é fornecido e os mesmos erros são apresentados, inclusive o erro de falta do package.json.

Parece que o SDK não está sendo reconhecido.

Seguei todas as instruções minuciosamente, pode ser versão do cordova?

**Comment by victormendes5** [comment]
Boa noite @limatheus e @igortrinidad. Eu não estou atuando mais nesse projeto. O responsável por ele agora é o @filpgame. Vou entrar em contato com ele e pedir pra ver o que está acontecendo.

**Comment by igortrinidad** [comment]
Boa noite @victormendes5 , obrigado pela atenção. 
Vamos aguardar o retorno do @filpgame então.
Abs

**Comment by limatheus** [comment]
@filpgame poderia nos ajudar?

Precisaremos implementar este plugin em um projeto e infelizmente até agora não conseguimos realizar a instalação.

**Comment by filpgame** [comment]
Boa tarde pessoal. 
Subi um fix recentemente no plugin (https://github.com/stone-payments/plugin-cordova/commit/9b4bf77803e44e6427e244508662e65189d4306f), o `package.json` estava apontando pra um arquivo inexistente.

**Comment by limatheus** [comment]
@filpgame nós notamos isso e criamos um fork para tentar ver se rodava, porém também não funcionou.

Outro erro que acontece é na hora de rodar o comando para instalar o plugin, acusando a falta do package.json. Vejo o erro abaixo:

```bash
cordova plugin add https://github.com/stone-pagamentos/plugin-cordova.git
(node:15683) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): CordovaError: Failed to fetch plugin https://github.com/stone-pagamentos/plugin-cordova.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: git+https://github.com/stone-pagamentos/plugin-cordova.git.
npm ERR! package.json npm can't find a package.json file in your current directory.
(node:15683) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Para contornar o erro de instalaçao adicionamos um package.json no fork só ai conseguimos intalar.

Tentamos adicionar até os Sdks 2.5.2 e o arquivo sdk_stone_2.2.10_fat.jar para testar, também adicionamos um package.json, mas não obtivemos nenhum sucesso.

O fork está neste repositório: https://github.com/igortrinidad/cordova-plugin-stone-sdk

**Comment by filpgame** [comment]
hmm, entendi. Tô dando uma olhada agora

**Comment by igortrinidad** [comment]
Show @filpgame , estamos na torcida!

Você acha possível também alterar o nome do plugin para o nome da convenção utilizada nos plugins Cordova?
Ex:

"cordova-plugin-inappbrowser"
"cordova-plugin-fcm"
"cordova-plugin-whitelist"

O exemplo do plugin Stone poderia ser:
"cordova-plugin-stone"
"cordova-plugin-stone-sdk"

Quando for disponibiliza-lo no npm fica simples a instalação pelo comando

`cordova add plugin cordova-plugin-stone`

Se sim, você deve alterar a variável name no package.json e o id no plugin.xml além de alterar o nome aqui no repo.

Abs

**Comment by filpgame** [comment]
galera, só pra alinhar. Depois que vocês colocaram o `package.json` no fork de vocês vocês continuaram recebendo o mesmo erro ou é diferente? Se for diferente, qual é? é esse?
```
(node:58832) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin https://github.com/stone-pagamentos/plugin-cordova.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
    at C:\Users\frodrigues\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\fetch.js:173:37
    at _rejected (C:\Users\frodrigues\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:864:24)
    at C:\Users\frodrigues\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\frodrigues\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\frodrigues\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\frodrigues\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\Users\frodrigues\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:137:13)
    at flush (C:\Users\frodrigues\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:150:11)
(node:58832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by igortrinidad** [comment]
Opa @filpgame , acho que a variável name do plugin está diferente do nome do repo e por isso esse erro...

Tenta alterar o nome do repo para igual à variável name no package.json

Nome do repo
`cordova-plugin-stone-sdk`

package.json:

`{
    "version": "1.0.1",
    "name": "cordova-plugin-stone-sdk",
    "cordova_name": "Cordova Stone Plugin",
    "description": "Cordova wrapper for Stone Mobile SDK",
    "issue": "https://github.com/stone-payments/plugin-cordova/issues",
    "license": "MIT",
    "author": {
        "name": "Stone",
        "email": "integracoes@stone.com.br"
    },
    "cordova": {
        "id": "cordova-plugin-stone-sdk",
        "platforms": [
            "ios",
            "android"
        ]
    },
    "repository": {
        "type": "git",
        "url": "https://github.com/stone-payments/cordova-plugin-stone-sdk.git"
    },
    "keywords": [
        "ecosystem:cordova",
        "cordova-android",
        "cordova-ios",
        "ios",
        "android",
        "cordova"
    ],
    "engines": [],
    "englishdoc": ""
}
`

**Comment by filpgame** [comment]
Não tinha atualizado a página e nem vi seu comentário sobre a convenção hahaha. Alterei o nome do repo

**Comment by igortrinidad** [comment]
Nice @filpgame !

Fiz um pull com a url novo no package.json, testei aqui e instalou e desinstalou sem erro (veja anexo)... Mas ainda não gerei o build, você conseguiu testar o build ai?

![captura de tela 2018-01-11 as 18 07 27](https://user-images.githubusercontent.com/13478652/34845090-dd79a7b2-f6fa-11e7-9cfd-d6babdb5caa9.png)

**Comment by filpgame** [comment]
testei e ainda não está encontrando as classes da lib que o plugin usa, to vendo o que pode ser

**Comment by igortrinidad** [comment]
Verdade, aqui ainda estou com outros problemas na instalação... Mas o @limatheus conseguiu instalar e encontrar esse erro...

Conferindo aqui o arquivo plugin.xml

Notei que tem uma diferença entre os sources, vou fazer um pull para você testar ai pf....

**Comment by igortrinidad** [comment]
Sorry @filpgame são as changes do commit que você fez ai... rsrsr

**Comment by filpgame** [comment]
hahahaha beleza

**Comment by igortrinidad** [comment]
Vocês sabem o que isso significa né @filpgame e @limatheus ? 

\o/ \o/ \o/\o/

![captura de tela 2018-01-12 as 03 37 34](https://user-images.githubusercontent.com/13478652/34861166-fdd443c4-f749-11e7-9cba-aab687c51367.png)

**Comment by filpgame** [comment]
shooow! 
Foi necessário fazer mais alguma alteração no plugin?

**Comment by igortrinidad** [comment]
@filpgame isso mesmo, só essas alterações ai... 

Mas depois de remover o repo e instalar de novo tudo,  o erro na linha 154 do stoneSDK.java parou, porém agora tem o erro do método validation que está quebrando o app... Pior que sem nenhum log, mas agora você já consegue testar ai e ver essa parte da SDK...

**Comment by filpgame** [comment]
Fechando pra seguir o assunto na #12
